site_name: PSCloudPC
site_url: https://Windows365Management.github.io/PSCloudPC
nav:
  - Home:
      - 'Introduction': 'index.md'
  - 'User Guide':
    - Cmdlets:
      - 'Connect-Windows365': 'cmdlets/Connect-Windows365.md'
      - 'Get-CloudPC': 'cmdlets/Get-CloudPC.md'
      - 'Get-CPCAzureNetworkConnection': 'cmdlets/Get-CPCAzureNetworkConnection.md'
  - 'Contributing': 'contributing/contribution-guidelines.md'
plugins:
  - search
  - include_dir_to_nav
  - social

theme:
  name: 'material'
  logo: Images/PSCloudPC_logo.png
  favicon: Images/favicon.ico
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - search.share
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 0
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html

extra:
  analytics:
    provider: google
    property: G-6HN1ZGL8WJ

repo_url: https://github.com/Windows365Management/PSCloudPC
copyright: PSCloudPC