site_name: PSCloudPC
site_url: https://Windows365Management.github.io/PSCloudPC
nav:
  - Home:
      - 'About PSCloudPC': 'index.md'
  - 'User Guide':
    - Cmdlets:
      - 'Connect-Windows365': 'cmdlets/Connect-Windows365.md'
      - 'Get-CloudPC': 'cmdlets/Get-CloudPC.md'
      - 'Get-CPCAzureNetworkConnection': 'cmdlets/Get-CPCAzureNetworkConnection.md'
  - 'Contributing': 'contributing/contribution-guidelines.md'
plugins:
  - search
  - include_dir_to_nav
  - social

theme:
  name: 'material'
  logo: Images/PSCloudPC_logo.png
  favicon: Images/favicon.ico
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - search.share
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 0
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html

extra:
  analytics:
    provider: google
    property: G-6HN1ZGL8WJ
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
repo_url: https://github.com/Windows365Management/PSCloudPC
copyright: PSCloudPC